name: "Quote - README"
author: Siddharth Chandra
description: "Update a section with random quote/fun-fact on your Readme"

inputs:
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    required: true
    default: ${{ github.token }}

  REPOSITORY:
    description: "Your GitHub repository"
    default: ${{ github.repository }}
    required: false

  OPTION:
    description: "Option for quote, fun-fact or both, it can take - quote, funfact or both"
    default: "both"
    required: false

  COMMIT_AUTHOR_EMAIL:
    description: "Add a commit author email of your choice"
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    required: false

  COMMIT_AUTHOR_NAME:
    description: "Add a commit author name of your choice"
    default: "github-actions[bot]"
    required: false

  COMMIT_EMAIL:
    description: "Add a commit email of your choice"
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    required: false

  COMMIT_USERNAME:
    description: "Add a commit username of your choice"
    default: "github-actions[bot]"
    required: false

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Update with quote-readme"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "bookmark"
  color: "orange"
